# Generated by Django 5.2 on 2025-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='access_token',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
