# Generated by Django 5.2 on 2025-05-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0002_session_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='access_token',
        ),
    ]
