# Generated by Django 5.2 on 2025-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0004_session_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
