# Generated by Django 5.2 on 2025-10-26 18:01

import fotoapp.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0005_alter_session_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cena zdjęcia w PLN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=fotoapp.models.photo.session_directory_path),
        ),
    ]
